MODULE PARAM
	! PARAMETERS.
	INTEGER(4), PARAMETER :: NRINTERIOR = 256
	INTEGER(4), PARAMETER :: NZINTERIOR = 64
	REAL(8), PARAMETER :: DR = 0.0625
	REAL(8), PARAMETER :: DZ = 0.25
	CHARACTER(LEN=*), PARAMETER :: ORDER = 'FOUR'
	! GRID VARIABLES.
	INTEGER(4) :: GHOST, NRTOTAL, NZTOTAL, ARRAY_DIM
END MODULE PARAM

PROGRAM ELLSOLVE_F90
	! GLOBAL PARAMETERS.
	USE PARAM
	! START DECLARATION.
	IMPLICIT NONE 
	! GRID FUNCTIONS.
	REAL(8), DIMENSION(:), ALLOCATABLE :: R, Z, U, F, S, RES
	! AUXILIARY VARIABLES.
	REAL(8) :: AUX_R, AUX_Z
	INTEGER(4) :: I, J, K

	! PROCESS PARAMETERS.
	! FIRST GET FINITE DIFFERENCE ORDER.
	IF (ORDER == 'TWO') THEN
		GHOST = 2
	ELSEIF (ORDER == 'FOUR') THEN
		GHOST = 3
	END IF
	! CALCULATE LONGITUDINAL DIMENSIONS.
	NRTOTAL = GHOST + NRINTERIOR + 1
	NZTOTAL = GHOST + NZINTERIOR + 1
	! TOTAL GRID SIZE.
	ARRAY_DIM = NRTOTAL * NZTOTAL

	! PRINT INFO TO SCREEN.
	PRINT *, 'ELLSOLVE_F90: System parameters are:'
	PRINT *, '		NrInt	= ', NRINTERIOR
	PRINT *, '		NzInt	= ', NZINTERIOR
	PRINT *, '		ghost	= ', GHOST
	PRINT *, '		dr	= ', DR
	PRINT *, '		dz	= ', DZ
	PRINT *, '		order	= ', ORDER

	! ALLOCATE GRID FUNCTIONS.
	PRINT *, 'ELLSOLVE_F90: Allocating memory...'
	ALLOCATE(R(ARRAY_DIM), Z(ARRAY_DIM), U(ARRAY_DIM), F(ARRAY_DIM), S(ARRAY_DIM), RES(ARRAY_DIM))
	PRINT *, 'ELLSOLVE_F90: Allocated memory.'

	! FILL GRIDS.
	!$OMP PARALLEL SHARED(R, Z, U, F, S, RES) PRIVATE(AUX_R, AUX_Z, J, K)
	!$OMP DO SCHEDULE(GUIDED)
	DO I = 1, NRTOTAL
		AUX_R = (DBLE(I - GHOST) - 0.5) * DR
		DO J = 1, NZTOTAL
			AUX_Z = (DBLE(J - GHOST) - 0.5) * DZ
			K = IDX(I, J)
			R(K) = AUX_R
			Z(K) = AUX_Z
			U(K) = 1.0
			F(K) = 0.0
			RES(K) = 0.0
			S(K) = EXP(-AUX_R**2-AUX_Z**2) * (0.5 + AUX_R**2 * (-3.0 + AUX_R**2 + AUX_Z**2))
		END DO
	END DO
	!$OMP END DO
	!$OMP END PARALLEL
	PRINT *, 'ELLSOLVE_F90: Filled and printed r, z grids.'


	! DEALLOCATE MEMORY.
	PRINT *, 'ELLSOLVE_F90: Deallocating memory...'
	DEALLOCATE(R, Z, U, F, S, RES)
	PRINT *, 'ELLSOLVE_F90: Deallocated memory.'

	CONTAINS
	INTEGER(4) FUNCTION IDX(I, J)
		INTEGER(4), INTENT(IN) :: I, J

		IDX = I * (NZTOTAL - 1) + J

		RETURN
	END FUNCTION IDX
END PROGRAM ELLSOLVE_F90
