PROGRAM FORTRAN_TEST

! USE ISO BINDINGS FOR C SIZES.
USE ISO_C_BINDING

IMPLICIT NONE
INTEGER(C_INT) :: NRINTERIOR, NZINTERIOR

NRINTERIOR = 128
NZINTERIOR = 128

PRINT*, 'FORTRAN_TEST: NRINTERIOR = ', NRINTERIOR, ' NZINTERIOR = ', NZINTERIOR

PRINT *, 'FORTRAN_TEST: INITIALIZING PARDISO PARAMETRERS AND MEMORY.'
CALL PARDISO_INIT(NRINTERIOR, NZINTERIOR)
PRINT *, 'FORTRAN_TEST: INITIALIZATION DONE.'

PRINT *, 'FORTRAN_TEST: CLEARING PARDISO MEMORY AND PARAMETERS.'
CALL PARDISO_DIE()
PRINT *, 'FORTRAN_TEST: ALL CLEAR.'

END PROGRAM FORTRAN_TEST
